[package]
name = "redflag"
version = "0.1.1"
edition = "2021"
description = "Lightweight secret scanner for codebases"
license = "MIT"
repository = "https://github.com/iammerus/redflag"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
walkdir = "2.3"
regex = "1.9"
serde = { version = "1.0", features = ["derive"] }
toml = "0.7"
thiserror = "1.0"
serde_json = "1.0"
chrono = "0.4"
git2 = { version = "0.20.0", features = ["vendored-openssl"] }
glob = "0.3"
tempfile = "3.3"
aho-corasick = "1.1"
sha2 = "0.10"
similar = { version = "=3.2.0", default-features = false, features = ["std"] }
base64 = "=0.22.1"
